# 表结构, 数据更新
mysql.data:
	mysql -f -h127.0.0.1 -P3306 -uroot < ./sql/user.sql
	mysql -f -h127.0.0.1 -P3306 -uroot < ./sql/order.sql
	mysql -f -h127.0.0.1 -P3306 -uroot < ./sql/order_detail.sql
	mysql -f -h127.0.0.1 -P3306 -uroot < ./sql/account.sql